export const ADD_SENTENCE_EVENT_RESULT = 'ADD_SENTENCE_EVENT_RESULT'
export const SET_DEFAULT_CHILD_SENTENCE_ID = 'SET_DEFAULT_CHILD_SENTENCE_ID'
export const SET_INPUT_PARENT_SENTENCE_ID = 'SET_INPUT_PARENT_SENTENCE_ID'
export const SET_INPUT_SENTENCE = 'SET_INPUT_SENTENCE'
